### ISSUE TITLE
add isolines labels options

### ISSUE THREAD

**Issue by jamarav** [clauswilke/ggisoband#5]
Hi everybody,

I would like to know if it could be possible to add labels in the isolines for this ggplot interface.
Firstly, I tried to convert grobs into ggplot objects with the `ggplotify()` package using the native functions included in the `isoband` package, but this is not a good solution. I can't to add the colorbar and the ggplot objects don't save the original x and y scales.
A second option could be to use the `isolines_grob()` function from the isoband package. I'm not sure if this is easy to implement. I've been trying to implement these changes in the `ggisolines()` function. Unfortunately I'm not sufficiently familiar with grobs objects. The function `ggisolines` creates several lists with all the isolines (`bandgrobs` and `linegrobs`).
Would it be possible to directly implement in a simple way the use of the native functions of the `isoband` package (`isobands_grob` and `isolines_grob`)?
In my opinion these changes would improve the interface in ggplot adding all the functionalities of the package `isoband`.

Thanks in advance

**Comment by clauswilke** [comment]
This package is no longer actively maintained, as isoband is now being used natively by ggplot2. You could look into taking the code from `geom_contour()` and plugging in `isolines_grob()`. I believe somebody wanted to do this for some extension package but nobody has as of today as far as I'm aware.

**Comment by jamarav** [comment]
Thanks @clauswilke for the quick response. I close the issue.
